# Project information
site_name: "Tada!: auTomAtic orDer-of-growth Analysis"
site_description: Tada! Docs
# site_author:
# site_url:

# Repository
repo_name: Tada-Project/tada
repo_url: https://github.com/Tada-Project/tada

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Page
nav:
  - Getting Started: getting-started.md
  - Using Tada: using-tada.md
  - Contributing: contributing.md
